### PR TITLE
list global marks

### LINKED ISSUE #88: what about global marks?
At the very least, it would be nice to be able to pullup a list of all global file marks and jump to it (similar to the m/ and m? functionality, except that for global file marks).

### PR DESCRIPTION
**Pull request by acornejo**
closes #88

### CODE REVIEW

**Comment by balta2ar** [comment]
@acornejo ping? I miss this feature.

**Comment by kshenoy** [comment]
@balta2ar Hi, can you elaborate what functionality you're talking about?

**Comment by ezuk** [comment]
+1 for this issue. It would be good to have a list showing all global marks, similar to m/ but for ABC etc.

**Comment by kshenoy** [comment]
Hi, a lot of code had changed and I couldn't merge this in. 

Can you try using `:SignatureListGlobalMarks` and see if it works and if this meets your requirements.

Note that SignatureListMarks has been renamed to SignatureListBufferMarks and I've added a new command SignatureListGlobalMarks. I'm using 'local' and 'global' to indicate the type of mark and 'buffer' to denote the scope.

**Comment by vigilancer** [comment]
@acornejo 
In my opinion `SignatureListGlobalMarks` closes your use case.
Is this PR still relevant?

**Pull request closed without merging**
